APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:dcnQWwYXJQKcTIN62Q6TFR5ap5WpPbofm35ig+gwdd0=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=portalub_ubn
DB_USERNAME=portalub_ubn
DB_PASSWORD=ubP1M5tkEYX2

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=server44.digilifes.com
MAIL_PORT=465
MAIL_USERNAME=admin@portal.ubncommunity.com
MAIL_PASSWORD=qPMOjS1LM9DA
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=admin@portal.ubncommunity.com
MAIL_FROM_NAME="${APP_NAME}"


AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_HOST=
PUSHER_PORT=443
PUSHER_SCHEME=https
PUSHER_APP_CLUSTER=mt1

VITE_APP_NAME="${APP_NAME}"
VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
VITE_PUSHER_HOST="${PUSHER_HOST}"
VITE_PUSHER_PORT="${PUSHER_PORT}"
VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

# RAZORPAY_KEY=rzp_live_H7CXXKrUzeihYD
# RAZORPAY_SECRET=NdzgeIq6fSNroZVEB0grjvpm

RAZORPAY_KEY=rzp_live_EwpHqAt1Nd72sl
RAZORPAY_SECRET=Fx6GEFlF20k5DTtzLEVer7Qt

BASE_URL='https://ubnmart.ubncommunity.com/api/registerUser'


REVERB_APP_ID=138062
REVERB_APP_KEY=dq2xr1zcj8tgokabjc2z
REVERB_APP_SECRET=bybr5f8oyfgwsyfa1uti
REVERB_HOST=localhost
REVERB_PORT=8080
REVERB_SCHEME=http

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
